version: '3.8'

services:
  mongo:
    container_name: mongodb
    image: mongo:4.2.20-rc0
    ports: 
      - "27017:27017"
      - "28017:28017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=api
      - ME_CONFIG_MONGODB_ADMINPASSWORD=docker1234
      - ME_CONFIG_MONGODB_SERVER=mongodb