version: '3'

services:
  intro:
    build:
      context: ./intro
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - log_intro:/var/log
    container_name: intro

  hidden:
    build:
      context: ./hidden
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    volumes:
      - log_hidden:/var/log
    container_name: hidden

  calling:
    build:
      context: ./calling
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - log_calling:/var/log
    container_name: calling

  cooked:
    build:
      context: ./cooked
      dockerfile: Dockerfile
    ports:
      - "4008:4008"
    volumes:
      - log_cooked:/var/log
    container_name: cooked

volumes:
  log_intro: {}
  log_hidden: {}
  log_calling: {}
  log_cooked: {}
