service: serverless-api

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
