service: serverless-api

# Create an optimized package for our functions
package:
  individually: true

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-plugin-typescript

useDotenv: true

custom:
  bundle:
    linting: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
