version: '3'

services:
  intro:
    build:
      context: ./intro
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    container_name: intro

  platform:
    build:
      context: ./platform
      dockerfile: Dockerfile
    ports:
      - "7005:7005"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    container_name: platform

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
