version: '3'

services:
  intro:
    build:
      context: ./intro
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - log_intro:/var/log
    container_name: intro

  error:
    build:
      context: ./error
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - log_error:/var/log
    container_name: error

  whoami:
    build:
      context: ./whoami
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - log_whoami:/var/log
    container_name: whoami

  forum:
    build:
      context: ./forum
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - log_forum:/var/log
    container_name: forum


volumes:
  log_intro: {}
  log_error: {}
  log_whoami: {}
  log_forum: {}
